AWSTemplateFormatVersion: 2010-09-09
Resources:
  incomingDLQ:
    Type: 'AWS::SQS::Queue'
    Properties: { "QueueName" : "incomingDLQ", "MessageRetentionPeriod": 1209600  }
  webhookDLQ:
    Type: 'AWS::SQS::Queue'
    Properties: { "QueueName" : "webhookDLQ", "MessageRetentionPeriod": 1209600  }
  webhookQueue:
    Type: 'AWS::SQS::Queue'
    Properties: { "QueueName" : "webhookQueue", "VisibilityTimeout": 60, "RedrivePolicy" : { "deadLetterTargetArn" : !GetAtt webhookDLQ.Arn, "maxReceiveCount" : 3 } }
  incomingQueue:
    Type: 'AWS::SQS::Queue'
    Properties: { "QueueName" : "incomingQueue", "VisibilityTimeout": 720, "RedrivePolicy" : { "deadLetterTargetArn" : !GetAtt incomingDLQ.Arn, "maxReceiveCount" : 3 } }
