exclude_statuses = [
    "Available For Adoption",
    "Hold",
    "Hold Finder",
    "Protective Custody/Hold",
    "Protective Custody/Transferred Ownership",
    "Due For Release",
    "Hold For Possible Match",
    "Hold In Foster",
    "Protective Custody In Foster",
    "Hold On Property Check",
    "Hold In Vet Care",
    "Police Hold",
    "Hold Quarantine",
    "Euthanized Adoptable",
    "Awaiting Euthanasia",
    "Bite Quarantine",
    "Emergency Boarding",
    "Hold Euthanasia",
    "Court Hold",
    "Wildlife Due For Release",
    "Stray Hold",
    "Awaiting Rescue",
    "Trial Adoption",
    "Emergency Evacuation - Temporary",
    "Awaiting Final Disposition",
    "Owner Hold",
    "Protective Custody Hold Quarantine",
    "Adopted - Awaiting Spay / Neuter",
    "PAT",
    "Available for Adoption - Offsite",
    "Available for Adoption - Awaiting Spay/Neuter",
    "Stray - In Foster",
    "Available for Adoption - Waiting Space",
    "Sanctuary/Life Resident",
    "Reclaimed - Awaiting Spay / Neuter",
    "Protective Custody - Awaiting Foster",
    "Sanctuary/Life Resident - Upload to Public Site",
    "Emergency Evacuation - In Foster",
    "Adopted - Awaiting Pickup",
    "ID Trace",
    "Bite Quarantine/RTO",
    "Available For Adoption - No Web Presence",
    "Stray Hold - In Vet Care",
    "Stray Hold - Awaiting transfer",
    "Bite Quarantine - In Foster",
    "Transfer Out - Awaiting Pickup"
]

def filter(animal):
    return animal['Status']['UriValue']['IsInCare'] and (animal['Status']['Name'] not in exclude_statuses) 

days = 30
